version: '3.8'
services:

  mysqldb:
    image: mysql:8.0.21
    restart: always
    environment:
      - MYSQLDB_USER=root_user
      - MYSQL_ROOT_PASSWORD=fIz^Kf#2K82RLQyP
      - MYSQL_DATABASE=spring_chat_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar ./app.jar
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/spring_chat_db
      - SPRING_DATASOURCE_USERNAME=root_user
      - SPRING_DATASOURCE_PASSWORD=fIz^Kf#2K82RLQyP
    image: 'roman2301/crm_sparta'
    ports:
      - 5050:8080
    depends_on:
      - mysqldb
    links:
      - mysqldb
volumes:
  db:
